### PR TITLE
Changed syntax to ES6 class structure

### PR DESCRIPTION
**Pull request by JoergAtGithub**
@DJPhatso In this PR I converted your code in the new ES6 class syntax, which we use for Mixxx 2.4.

Please test the modified Hercules-DJControl-MIX-scripts.js file with your controller. If everything works as before, Merge this into your branch by pressing the green button below.

### CODE REVIEW

**Comment by DJPhatso** [comment]
Doesn't work. Found a syntax error at line 1.

Would anything need to be changed in the .xml file as well ?

**Comment by JoergAtGithub** [comment]
What does it report?
XML-File needs no change.

**Comment by DJPhatso** [comment]
image

**Comment by JoergAtGithub** [comment]
Did you use Mixxx 2.4 or 2.3?

**Comment by DJPhatso** [comment]
Ah, yes. Still using 2.3.6. My bad...

Let me change that.

**Comment by DJPhatso** [comment]
All seems good with the latest 2.4 beta.

**Comment by JoergAtGithub** [comment]
Test it carefully, before merging...

**Pull request merged**
